[project]
name = "stage-three"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk[all]>=0.3.10",
    "fastapi[standard]>=0.120.3",
    "google-genai>=1.47.0",
    "reddis>=1.0.1",
]
